In [1]:
list1 = [5,8,9,15,35,52,26,4,20]


In [2]:
mean_list1 = sum(list1) / len(list1)
mean_list1

19.333333333333332

In [3]:
def mean(input_list):
    mean = sum(input_list) / len(input_list)
    return mean

In [4]:
mean(list1)

19.333333333333332

In [5]:
def median(input_list):
    input_list.sort()
    length = len(input_list)
    if length % 2 == 0: # for even number of numbers
        # first position
        first_position = input_list[length//2]
        second_position = input_list[length//2-1]
        median = (first_position + second_position) / 2
    else: # for odd number of numbers
        median = input_list[length//2]
    return median

In [6]:
list1[len(list1)//2]

35

In [7]:
list1[len(list1)//2-1]

15

In [8]:
median(list1)

15

In [9]:
list1.append(21)

In [10]:
median(list1)

17.5

In [11]:
def stdev(input_list):
    squared_list = []
    n = len(input_list)
    mean = sum(input_list) / n
    for i in input_list:
        squared_list.append((i-mean)**2)
    sq_sum = sum(squared_list)
    variance = sq_sum / n
    stdev = variance ** (1/2)
    return stdev

In [12]:
stdev(list1)

14.333527130472806

In [13]:
pip install numpy

     --------------------------------------- 15.0/15.0 MB 23.3 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [14]:
import numpy as np

In [15]:
array_1d = np.array(list1)

In [16]:
array_1d

array([ 4,  5,  8,  9, 15, 20, 21, 26, 35, 52])

In [18]:
array_1d.min

<function ndarray.min>

In [19]:
array_1d.min()

4

In [20]:
array_1d.mean()

19.5

In [21]:
array_1d.std()

14.333527130472806

In [22]:
array_2d = np.array([list1,list1])

In [23]:
array_2d

array([[ 4,  5,  8,  9, 15, 20, 21, 26, 35, 52],
       [ 4,  5,  8,  9, 15, 20, 21, 26, 35, 52]])

In [24]:
print(array_2d)

[[ 4  5  8  9 15 20 21 26 35 52]
 [ 4  5  8  9 15 20 21 26 35 52]]


In [25]:
array_5d = np.array([1,2,5,6,8], ndmin=5)

In [26]:
array_5d

array([[[[[1, 2, 5, 6, 8]]]]])

In [27]:
print(array_5d)

[[[[[1 2 5 6 8]]]]]
